links:
  - name: Top
    desc: トップページです。
    url: /index.html
  - name: Profile
    desc: このサイトの管理人のプロフィールです。
    url: /wp/index.html
  - name: Contents
    desc: サイトコンテンツを紹介します。
    url: /wp/contents.html
  - name: Links
    desc: 関連サイトへのリンク集です。
    url: /wp/links.html

mathjax:
  url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  polyfill: https://polyfill.io/v3/polyfill.min.js?features=es6
